version: '3'

services:

  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:14.2'
    platform: linux/arm64/v8 # added for M1 Mac
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: concurrency
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
      # delete the existing database files in the ./db-data/postgres/ directory once if you want to initialize a new database
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  #  start Redis, and ensure that data is stored to a mounted volume
  redis:
    image: 'redis:alpine'
    platform: linux/arm64/v8 # added for M1 Mac
    ports:
      - "6399:6399"
    restart: always
    volumes:
      - ./db-data/redis/:/data

  #  start mailhog
  mailhog:
    image: 'mailhog/mailhog:latest'
    platform: linux/amd64 # added for M1 Mac
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

